### ISSUE TITLE
`parseInt` on `window.devicePixelRatio`

### ISSUE THREAD

**Issue by Sysix** [damianobarbati/get-browser-fingerprint#16]
Hey, I looked at the source code and was questioning myself, why `window.devicePixelRatio` is put into `parseInt`.

There are some problems with it:

1. devicePixelRatio is a floating number, see the docs: https://developer.mozilla.org/en-US/docs/Web/API/Window/devicePixelRatio#value
2. parseInt expects a string. so `window.devicePixelRatio.toString()` should be the right way
3. Why at all parse it as a int? some ratio can be 1,5 or similar

**Comment by damianobarbati** [comment]
@Sysix good point, no need for that.
