### ISSUE TITLE
fingerprint changes

### ISSUE THREAD

**Issue by fishuke** [damianobarbati/get-browser-fingerprint#17]
I am trying to limit my chrome extension for one browser and i was using this library and fingerprint is changing what should we do?

**Comment by damianobarbati** [comment]
@fishuke weird, the fingerprint changes everytime you call the function in the background.js? Maybe chrome is doing some kind of anti-fingerprinting in the extensions context, not sure about it.

**Comment by fishuke** [comment]
Been using it and a lot of report from customers that their fingerprint changes after sleep or restart... happened for me several times

**Comment by fishuke** [comment]
@damianobarbati customers with stable connection doesn't have problems but some customers says it might happen with different wifi & network connections. I reviewed the source code and couldn't find what might be the reason. Any ideas?

**Comment by damianobarbati** [comment]
@fishuke very weird, I can't find anything in the code that could be responsible for this. Even if they were switching back and forth from fiber/adsl connection to 4g connection, I don't think this could affect anyhow the current data retrieved to compute the fingerprint. 

No idea for now.

**Comment by fishuke** [comment]
I was looking for another library and I just saw the reason. Screen res. I also just realized there is another issue as well. Different screen sizes.

**Comment by damianobarbati** [comment]
@fishuke  I added an enableScreen param in the latest version, set it to false and let me know if it works for you. Reopen this issue if not!

**Comment by fishuke** [comment]
@damianobarbati thanks we used the unique canvas fingerprint only and it works stable.
