### ISSUE TITLE
Same fingerprint after browser update

### ISSUE THREAD

**Issue by Twiisterson** [damianobarbati/get-browser-fingerprint#18]
After updating browser (Firefox), calculated fingerprint has not changed, despite the version change

**Comment by schorsch** [comment]
Yes, this is the same e.g. for chrome. For my use-case this is perfectly OK.
I cannot image that detecting new devices every other day, if you look at the release rates of chrome, would be very practical.

**Comment by damianobarbati** [comment]
@Twiisterson I think this is actually good. Considering Chrome has a new release every 5w or so, you would be assuming many different user when in fact is the always the same.
