### ISSUE TITLE
If the computer is connected to 2 different screens, access it with the same browser and each screen will generate a fingerprint.

### ISSUE THREAD

**Issue by hblab-khoipv** [damianobarbati/get-browser-fingerprint#19]
I open the same browser on 2 different monitors (15.6 inch laptop and 25 inch secondary monitor) and I get two fingerprints.
Can you fix it?
Thank you very much

**Comment by damianobarbati** [comment]
@hblab-khoipv I added an `enableScreen` param in the latest version, set it to false and let me know if it works for you. Reopen this issue if not!

**Comment by jbarmanet** [comment]
Hi,
Nice fix that works on my Mac computer, but not on Windows 10: still 2 different fingerprints even with the option  enableScreen set to false.
