### ISSUE TITLE
@types? 

### ISSUE THREAD

**Issue by carterjfulcher** [damianobarbati/get-browser-fingerprint#28]
Would be awesome to be able to use this natively with Typescript

**Comment by Sysix** [comment]
@damianobarbati I would like to work on it. You have prefer build framework? I see `vitest` already. So `vite`?  
Can give you also a `tsc`-only solution :)

**Comment by damianobarbati** [comment]
@Sysix what's the simplest one? I'm assuming a post-build step with tsc. What you think?

**Comment by Sysix** [comment]
@damianobarbati I created a simple build step with `tsc`. Some other ToDo's needed to be done by you :)

**Comment by carterjfulcher** [comment]
nice! thanks @Sysix @damianobarbati

**Comment by Sysix** [comment]
@damianobarbati u had any time to look into the PR? I could get more into it with backwards testing and co.

**Comment by amirzezo201** [comment]
is there any work around for the @types ?

**Comment by alphonso06** [comment]
Have tried using it in React app, the build fails without `@types`.

**Comment by damianobarbati** [comment]
Guys, types are no published from v3.2.3. Please reopen the issue if you still encounter issues.
