### ISSUE TITLE
Why stop support hardware only fingerprint?

### ISSUE THREAD

**Issue by temi4** [damianobarbati/get-browser-fingerprint#7]
Hello. 

Why you stop support hardware only fingerprint?
It's good functions

https://github.com/Song-Li/cross_browser - maybe useful for extending the library

**Comment by damianobarbati** [comment]
@temi4 interesting, I'll be giving a look soon and probably re-introduce hardware only fingerprinting.

The goal is to have it:
- lightweight
- synchronous
- thus fast

**Comment by damianobarbati** [comment]
@temi4 `hardwareOnly` param is back again from `v2.1.1`
