### ISSUE TITLE
Different fingerprints for the same browser

### ISSUE THREAD

**Issue by jbarmanet** [damianobarbati/get-browser-fingerprint#8]
Be careful, at least on Chrome Mac (Intel Mac OS 11.6.1 and Chrome 96) the results may be different on the same browser  depending how the page was opened.
The 2 culprits are the `mimeTypes` and the `plugins` variables.  

Example on a test page, if I copy-paste the address in a new Chrome tab I get this:
`"mimeTypes": [
		"application/pdf",
		"application/x-google-chrome-pdf",
		"application/x-nacl",
		"application/x-pnacl"
	],
	"plugins": [
		"Chrome PDF Plugin",
		"Chrome PDF Viewer",
		"Native Client"
	],`

Although if I click on a link that opens the exact same page in a Chrome tab I get this:
`"mimeTypes": [
		"application/pdf",
		"text/pdf"
	],
	"plugins": [
		"PDF Viewer",
		"Chrome PDF Viewer",
		"Chromium PDF Viewer",
		"Microsoft Edge PDF Viewer",
		"WebKit built-in PDF"
	],`

I did not dig further to understand why Chrome does not give the same info in these situations, but as a quick fix for that behavior you can remove those 2 const from the code.

**Comment by damianobarbati** [comment]
@jbarmanet vey weird, did you fork remove these?
